{"Package":{"Ecosystem":"pypi","Name":"request","Version":"1.0.117"},"CreatedTimestamp":1732266963,"Analysis":"[module] \u003cmodule 'site-packages.hmatch' from '/app/request/usr/lib/python3.12/site-packages/hmatch.py'\u003e\n[class] HTTPError\n[instance methods] HTTPError\nFailed to execute code for module \u003cmodule 'site-packages.hmatch' from '/app/request/usr/lib/python3.12/site-packages/hmatch.py'\u003e\nTraceback (most recent call last):\n  File \"/usr/local/bin/analyze-python.py\", line 144, in execute_module\n    do_execute(module)\n  File \"/usr/local/bin/analyze-python.py\", line 188, in do_execute\n    try_call_methods(instance, name, should_investigate, mark_seen)\n  File \"/usr/local/bin/analyze-python.py\", line 293, in try_call_methods\n    for method_name, method in inspect.getmembers(instance, is_non_init_method):\n  File \"/usr/lib/python3.10/inspect.py\", line 469, in getmembers\n    value = getattr(object, key)\n  File \"/usr/lib/python3.10/tempfile.py\", line 644, in __getattr__\n    setattr(self, name, a)\nTypeError: 'function' object cannot be interpreted as an integer\n[module] \u003cmodule 'requests' from '/usr/local/lib/python3.10/dist-packages/requests/__init__.py'\u003e\n[class] ConnectTimeout\n[instance methods] ConnectTimeout\n[class] ConnectionError\n[instance methods] ConnectionError\n[class] DependencyWarning\n\u003cclass 'ValueError'\u003e: no signature found for builtin type \u003cclass 'urllib3.exceptions.DependencyWarning'\u003e\nFailed to execute code for module \u003cmodule 'requests' from '/usr/local/lib/python3.10/dist-packages/requests/__init__.py'\u003e\nTraceback (most recent call last):\n  File \"/usr/local/bin/analyze-python.py\", line 144, in execute_module\n    do_execute(module)\n  File \"/usr/local/bin/analyze-python.py\", line 185, in do_execute\n    assert instance.__class__ == member\nAssertionError\n"}